project/hh_search/urls.py
from django.urls import path

from . import views


app_name = "work_search"


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("find_vacancies/", views.find_vacancies, name="find_vacancies"),
    path("change_blacklist/<int:pk>/", views.change_blacklist, name="change_blacklist"),
    path("employer_responded/<int:pk>/", views.employer_responded, name="employer_responded"),
    path("send_responses_to_vacancies/", views.send_responses_to_vacancies, name="send_responses_to_vacancies"),
    path("get_vacancies_list/", views.get_vacancies_list, name="get_vacancies_list"),

    path("vacancies_list/", views.vacancies_list, name="vacancies_list"),
    path("find_employer_name/", views.find_employer_name, name="find_employer_name"),
    path("get_bar_chart_data/", views.get_bar_chart_data, name="get_bar_chart_data"),
    path("infine_scroll_table/", views.infine_scroll_table, name="infine_scroll_table"),
    path("employer_filter_table/", views.employer_filter_table, name="employer_filter_table"),
    path("change_negotiations/<int:pk>/", views.change_negotiations, name="change_negotiations"),

]

project/settings/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("hh_search.urls", namespace="work_search")),
]

project/hh_search/models.py
from django.db import models


class FoundVacancies(models.Model):

    class SearchRequest(models.TextChoices):
        DJANGO = "django", "django"
        AIRFLOW = "airflow", "airflow"
        DATA_ENGINEER = "data engineer", "data engineer"
        DATA_ANALYST = "data analyst", "data analyst"
        PYTHON = "python", "python"


    search_request = models.CharField(max_length=20, choices=SearchRequest.choices, default=SearchRequest.DJANGO)
    vacancies_id = models.PositiveIntegerField()
    name = models.CharField(max_length=500)
    salary_from = models.FloatField(null=True, blank=True)
    salary_to = models.FloatField(null=True, blank=True)
    salary_currency = models.CharField(max_length=20)
    alternate_url = models.URLField()
    snippet_requirement = models.TextField(null=True, blank=True)
    snippet_responsibility = models.TextField(null=True, blank=True)
    schedule_name = models.TextField(max_length=300)
    employer_name = models.CharField(max_length=500)
    employer_alternate_url = models.CharField(max_length=500)
    employer_id = models.PositiveIntegerField(default=1)
    employer_rating = models.FloatField()
    employer_review_count = models.PositiveIntegerField()
    area_name = models.CharField(max_length=500)
    published_at = models.DateTimeField()
    created_at = models.DateTimeField()
    created_record = models.DateTimeField(auto_now_add=True)
    update_record = models.DateTimeField(auto_now=True)
    employer_responded = models.BooleanField(default=False)
    blacklist = models.BooleanField(default=False)
    negotiations = models.BooleanField(default=False)

    class Meta:
        ordering = ["-employer_rating", "-employer_review_count", "-published_at"]        

    def __str__(self):
        return self.name
    
class UserTokenModel(models.Model):
    user = models.SmallIntegerField()
    access_token = models.CharField(max_length=200)
    refresh_token = models.CharField(max_length=200)


    def __str__(self):
        return str(self.user)
    

class ResumeId(models.Model):
    name = models.CharField(max_length=20)
    search_request = models.CharField(max_length=20)
    resume_id = models.CharField(max_length=200)
    message = models.TextField()

    def __str__(self):
        return self.name
    
    

project/hh_search/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit, Row, Column

from django import forms

from .models import FoundVacancies


class FoundVacancisForm(forms.ModelForm):
    choices = FoundVacancies.SearchRequest.choices
    search_request = forms.ChoiceField(choices=choices, label="sdfsd")

    class Meta:
        model = FoundVacancies
        fields = {
            "search_request",
            "blacklist",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Row(
                Column("search_request"),
                Column("blacklist"),
            ),
        )

project/hh_search/views.py
import requests
import json
from flatten_json import flatten
import pandas as pd
import time

from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from django.conf import settings
from django.db.models import Count, Q
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

from .models import FoundVacancies, UserTokenModel, ResumeId
from . import utils, filters
from . import tasks


@login_required
def find_vacancies(request):
    if request.htmx:
        search_request = request.GET.get("search_request")
        user_id = request.user.id

        tasks.find_vacancies.delay(user_id, search_request)
        vacancies = {}
        context = {
            "vacancies": vacancies,
        }
        return render(request, "partials/tables/vacancies_list_table.html", context)
    else:
        find_vacancies_active_link = "active"
        choices = FoundVacancies.SearchRequest.choices
        vacancies = FoundVacancies.objects.filter(
            search_request=choices[0][0], negotiations=False
        )
        context = {
            "find_vacancies_active_link": find_vacancies_active_link,
            "choices": choices,
            "vacancies": vacancies,
        }
        return render(request, "hh_search/find_vacancies.html", context)


@login_required
def get_authorization_code(request):
    authorization_code = request.GET.get("code", "")
    context = {
        "authorization_code": authorization_code,
    }
    return render(request, "hh_search/get_authorization_code.html", context)


@login_required
def change_blacklist(request, pk):
    vacancy = FoundVacancies.objects.get(pk=pk)
    if request.GET.get("blacklist"):
        vacancy.blacklist = True
        vacancy.save()
    else:
        vacancy.blacklist = False
        vacancy.save()
    return HttpResponse("")


@login_required
def employer_responded(request, pk):
    vacancy = FoundVacancies.objects.get(pk=pk)
    if request.GET.get("employer_responded"):
        vacancy.employer_responded = True
        vacancy.save()
    else:
        vacancy.employer_responded = False
        vacancy.save()
    return HttpResponse("")


@login_required
def send_responses_to_vacancies(request):
    search_request = request.GET.get("search_request")
    vacancies = FoundVacancies.objects.filter(
        search_request=search_request,
        negotiations=False,
        blacklist=False,
    )
    user_id = request.user.id
    user_tokens = list(UserTokenModel.objects.filter(user=user_id).values())
    access_token = user_tokens[0].get("access_token")
    resume = list(ResumeId.objects.filter(search_request=search_request).values())[0]
    resume_id = resume.get("resume_id")
    resume_message = resume.get("message")

    [
        utils.send_response_to_employer(
            access_token, vacancy.vacancies_id, resume_id, resume_message
        )
        for vacancy in vacancies
    ]

    return HttpResponse("")


@login_required
def get_vacancies_list(request):
    search_request = request.GET.get("search_request")
    vacancies = FoundVacancies.objects.filter(
        search_request=search_request, negotiations=False
    )
    context = {
        "vacancies": vacancies,
    }
    return render(request, "partials/tables/vacancies_list_table.html", context)


@login_required
def vacancies_list(request):
    if request.htmx:
        print(request.GET)
        filter_set = filters.FoundVacancisFilter(
            request.GET, queryset=FoundVacancies.objects.all()
        )
        context = {
            "vacancies": filter_set.qs,
        }
        return render(request, "partials/tables/vacancies_list_table.html", context)
    else:
        vacancies_list_active_link = "active"
        choices = FoundVacancies.SearchRequest.choices
        init_filter = {
            "search_request": "django",
        }
        filter_set = filters.FoundVacancisFilter(
            init_filter, queryset=FoundVacancies.objects.all()
        )
        vacancies = filter_set.qs
        form = filter_set.form
        context = {
            "vacancies_list_active_link": vacancies_list_active_link,
            "choices": choices,
            "vacancies": vacancies,
            "form": form,
        }
    return render(request, "hh_search/vacancies_list.html", context)


@login_required
def find_employer_name(request):
    employer_name = request.GET.get("employer_name")
    vacancies = FoundVacancies.objects.filter(employer_name__icontains=employer_name)
    context = {"vacancies": vacancies}
    return render(request, "partials/tables/vacancies_list_table.html", context)


def dashboard(request):
    vacancies = FoundVacancies.objects.filter(blacklist=False)
    pagingator = Paginator(vacancies, 3)
    vacancies_page = pagingator.page(1)
    context = {
        "vacancies": vacancies_page,
    }
    return render(request, "hh_search/dashboard.html", context)


def get_bar_chart_data(request):
    bar_chart_data = (
        FoundVacancies.objects.filter(blacklist=False)
        .values("search_request")
        .annotate(total=Count("search_request"))
    )
    bar_chart_data = pd.DataFrame(bar_chart_data).to_json(orient="split")
    data = json.loads(bar_chart_data)
    return JsonResponse(data, safe=False)


def infine_scroll_table(request):
    filter = request.GET.get("search_field")

    page = request.GET.get("page", 1)
    vacancies = FoundVacancies.objects.filter(
        Q(blacklist=False),
        Q(employer_name__icontains=filter) | Q(search_request__icontains=filter),
    )
    pagingator = Paginator(vacancies, 3)
    vacancies_page = pagingator.page(page)

    context = {
        "vacancies": vacancies_page,
    }
    return render(request, "partials/tables/infine_scroll.html", context)


def employer_filter_table(request):
    filter = request.GET.get("search_field")
    page = request.GET.get("page", 1)
    vacancies = FoundVacancies.objects.filter(
        Q(blacklist=False),
        Q(employer_name__icontains=filter) | Q(search_request__icontains=filter),
    )
    pagingator = Paginator(vacancies, 3)
    vacancies_page = pagingator.page(page)

    context = {
        "vacancies": vacancies_page,
    }
    return render(request, "partials/tables/vacancies_list_table_dash.html", context)


@login_required
def change_negotiations(request, pk):
    vacancy = FoundVacancies.objects.get(pk=pk)
    if request.GET.get("negotiations"):
        vacancy.negotiations = True
        vacancy.save()
    else:
        vacancy.negotiations = False
        vacancy.save()
    return HttpResponse("")

project/hh_search/templates/hh_search/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Dashboard
{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <h1 class="text-center my-3">Dashboard</h1>
      <hr />
    </div>
    <div class="row" id="bar_chart"></div>
    <hr>
    <div class="row">
      <div class="col mb-3">
        <div class="input-group has-validation">
          <span class="input-group-text"><i class="bi bi-search"></i></span>
          <div class="form-floating is-invalid">
            <input type="text" class="form-control" id="search_field_dash" placeholder="Employer name"
            hx-get="{% url "work_search:employer_filter_table" %}"
            hx-trigger="keyup delay:0.4s changed"
            hx-target="#vacancies_table"
            hx-swap="innerHTML"
            hx-vals="js:{
              'search_field': $('#search_field_dash').val(),
            }"
            hx-indicator="#indicator"
            >
            <label for="employer_name_filter">Start to type employer name or search request name</label>
          </div>
        </div>
      </div>
    </div>
    <div class="row" id="vacancies_table">
      {% include "partials/tables/vacancies_list_table_dash.html" %}
    </div>
  </div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'hh_search/barChart.js' %}"></script>
{% endblock %}

project/hh_search/templates/hh_search/find_vacancies.html
{% extends 'base.html' %}

{% block title %}
  Find Vacancies
{% endblock %}

{% block content %}
<div class="container-flex p-3">
    <div class="row">
        <div class="col-11">
            <select id="search_request" class="form-select"
                name="search_request"
                hx-get="{% url "work_search:get_vacancies_list" %}"
                hx-trigger="change"
                hx-target="#vacancies_list"
                hx-swap="innerHTML"
                hx-indicator="#indicator"
                >
                {% include "partials/options/options.html" with elements=choices %}
            </select>
        </div>
        <div class="col-1">
            <button 
                type="button" 
                class="btn btn-success"
                hx-get="{% url "work_search:find_vacancies" %}"
                hx-vals="js:{
                    'search_request': $('#search_request').val(),
                }"
                hx-target="#vacancies_list"
                hx-indicator="#indicator"
                hx-swap="innerHTML"
                >Search
            </button>
        </div>
    </div>
    <div class="row">
        <div class="col mt-3">
            <button 
                type="button" 
                class="btn btn-secondary"
                hx-get="{% url "work_search:send_responses_to_vacancies" %}"
                hx-vals="js:{
                    'search_request': $('#search_request').val(),
                }"
                hx-target="this"
                hx-indicator="#indicator"
                hx-swap="none"
                >Sent response to vacancies 
            </button>
        </div>
    </div>
    <hr>
    <div class="row mt-3" id="vacancies_list">
        {% include "partials/tables/vacancies_list_table.html" %}
    </div>
</div>
{% endblock %}

project/hh_search/templates/hh_search/vacancies_list.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Vacancies list
{% endblock %}

{% block content %}
  <div class="container-flex p-3">
    {% crispy form %}
    <hr />
    <div class="row mt-3" id="vacancies_list">
      {% include 'partials/tables/vacancies_list_table.html' %}
    </div>
  </div>
{% endblock %}